language: bash
os: linux
sudo: enabled
env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8

install:
  - sudo apt update
  - sudo apt install -y snapd
  - sudo snap install lxd --channel 3.0/stable
  - sudo snap install snapcraft --candidate --classic
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - mkdir -p "$TRAVIS_BUILD_DIR/snaps-cache"
script:
  - export PATH=/snap/bin:$PATH
  - sudo snapcraft cleanbuild
  - ls -al
after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh ./gitkraken*.snap*
after_failure:
  - sudo journalctl -u snapd
  - sudo snap install http
  - /snap/bin/http https://api.snapcraft.io/v2/snaps/info/core architecture==amd64 Snap-Device-Series:16
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/