name: gitkraken
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: Unleash your repo.
description: |
  The best Git client should integrate with your Git hosting service. That’s why GitKraken connects to popular services like GitHub, Bitbucket and GitLab to make working with your remote repositories easier.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run-on: [amd64]

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes

parts:
  gitkraken:
    plugin: nil
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget https://www.gitkraken.com/download -q -S -O - 2>&1 | grep Latest | sed 's|</| |' | awk '{print $5}')
      echo $ver > $SNAPCRAFT_STAGE/version
      wget https://release.gitkraken.com/linux/gitkraken-amd64.deb && dpkg-deb -xv gitkraken-amd64.deb .
      cp -R -p usr $SNAPCRAFT_PART_INSTALL/
      sed -i 's|Icon=gitkraken|Icon=/usr/share/pixmaps/gitkraken\.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/gitkraken.desktop
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/sounds
    after:
      - desktop-gtk3
    build-packages:
      - wget
    stage-packages:
      - gconf2
      - gconf-service
      - libasound2
      - libnotify4
      - libxtst6
      - libxkbfile1
      - libxss1
      - libnss3
      - librtmp1
      - libcurl3
      - python
      - gvfs-bin
      - libgnome-keyring0
      - gir1.2-gnomekeyring-1.0
      - git
      - git-lfs
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/lintian
      - -usr/bin/gitkraken
      - -usr/share/themes
      - -usr/share/sounds

  desktop-gtk3:
    after:
      - git-lfs
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/lintian
      - -usr/share/themes
      - -usr/share/icons
      - -usr/share/sounds

  git-lfs:
    plugin: nil
    override-build: |
      curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
    build-packages:
      - curl
      - gnupg
      - software-properties-common
      - apt-transport-https

apps:
  gitkraken:
    command: bin/desktop-launch $SNAP/usr/share/gitkraken/gitkraken
    desktop: usr/share/applications/gitkraken.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to
    # ensure libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - browser-support
      - desktop
      - gsettings
      - home
      - network
      - opengl
      - unity7
      - wayland
      - x11
      - removable-media
      - ssh-keys
      - gpg-keys
